// Words for the Make Handouts page (the questions) and for the printed handout itself.

export const handoutUi = {
  en: {
    title: "Make handouts",
    intro:
      "Helping people on the street, at a shelter, or at church? Answer a few questions and print flyers to hand out. Each one shows the way to the closest free computer at a library, how to use Redemption, help nearby, and a word of hope.",
    qWhere: "Where will you hand these out?",
    qSpot: "Name of this spot",
    qSpotHint: "Optional. For example: “the bus stop at 7th and Congress.” It helps with directions.",
    qSpotPlaceholder: "Example: Republic Square Park",
    qNeeds: "What help should the handout list?",
    qNeedsHint: "Pick up to 4. We list the closest place for each.",
    qLang: "What language?",
    langEn: "English",
    langEs: "Español",
    langBoth: "Both (one of each)",
    qSize: "How big?",
    sizeFull: "1 big flyer per page",
    sizeHalf: "2 flyers per page (cut in half)",
    qDevotion: "Add a short devotional?",
    noDevotion: "No devotional",
    make: "Make my handout",
    needPlace: "First, tell us where you will hand these out (question 1).",
    previewTitle: "Your handout is ready",
    previewHint: "This is what will print. Print as many copies as you need.",
    print: "Print handouts",
    change: "Change answers",
    pages: (n: number) => (n === 1 ? "Prints on 1 page." : `Prints on ${n} pages.`),
  },
  es: {
    title: "Hacer volantes",
    intro:
      "¿Ayuda a personas en la calle, en un refugio o en la iglesia? Conteste unas preguntas e imprima volantes para repartir. Cada uno muestra cómo llegar a la computadora gratis más cercana en una biblioteca, cómo usar Redemption, ayuda cerca y una palabra de esperanza.",
    qWhere: "¿Dónde va a repartirlos?",
    qSpot: "Nombre de este lugar",
    qSpotHint: "Opcional. Por ejemplo: “la parada de autobús de la calle 7 y Congress”. Ayuda con las direcciones.",
    qSpotPlaceholder: "Ejemplo: Parque Republic Square",
    qNeeds: "¿Qué ayuda debe mostrar el volante?",
    qNeedsHint: "Elija hasta 4. Mostramos el lugar más cercano para cada una.",
    qLang: "¿En qué idioma?",
    langEn: "English",
    langEs: "Español",
    langBoth: "Los dos (uno de cada uno)",
    qSize: "¿De qué tamaño?",
    sizeFull: "1 volante grande por página",
    sizeHalf: "2 volantes por página (cortar a la mitad)",
    qDevotion: "¿Agregar un devocional corto?",
    noDevotion: "Sin devocional",
    make: "Hacer mi volante",
    needPlace: "Primero, díganos dónde va a repartirlos (pregunta 1).",
    previewTitle: "Su volante está listo",
    previewHint: "Así se va a imprimir. Imprima todas las copias que necesite.",
    print: "Imprimir volantes",
    change: "Cambiar respuestas",
    pages: (n: number) => (n === 1 ? "Se imprime en 1 página." : `Se imprime en ${n} páginas.`),
  },
};

export const handoutSheet = {
  en: {
    headline: "You are loved. You are not alone.",
    who: "Someone who cares gave you this paper. Redemption is a free Christian website that helps people in Texas find food, a place to sleep, showers, an ID, a phone, medical care, jobs, and more. It is free and private. You do not have to believe anything to get help.",
    whoShort: "Redemption is a free, private Christian website that helps people in Texas find food, a bed, showers, an ID, a phone, and more. Help is for everyone.",
    howTitle: "How to use Redemption for free",
    step1: "Go to the closest public library:",
    stepNoLibrary: "Ask anyone where the closest public library is. Or call 2-1-1.",
    from: (miles: string, dir: string, spot: string) => `About ${miles} ${dir} of ${spot}`,
    here: "here",
    walk: (min: string) => `about ${min} walking`,
    farWalk: "too far to walk, so ask about a bus",
    hours: "Hours",
    step2: "Ask at the front desk to use a free computer. No library card? Ask for a guest pass.",
    step3: "Open the internet and type:",
    step3b: "Then tap what you need.",
    scan: "Or scan with a phone camera",
    nearTitle: "Help near here",
    call211: "Call 2-1-1 any time. Free, 24 hours, any language.",
    crisis: "In crisis? Call or text 988.",
    emergency: "Emergency? Call 9-1-1.",
    hopeTitle: "A word of hope",
    prayer: "A prayer",
    footer: "Every person has worth. Every person can be redeemed.",
    miles: (m: number) => (m < 0.1 ? "0.1 miles" : m < 10 ? `${m.toFixed(1)} miles` : `${Math.round(m)} miles`),
    dirs: ["north", "northeast", "east", "southeast", "south", "southwest", "west", "northwest"],
    cut: "cut here",
  },
  es: {
    headline: "Usted es amado. No está solo.",
    who: "Alguien que se preocupa por usted le dio este papel. Redemption es un sitio web cristiano y gratis que ayuda a personas en Texas a encontrar comida, un lugar para dormir, duchas, una identificación, un teléfono, atención médica, trabajo y más. Es gratis y privado. No tiene que creer en nada para recibir ayuda.",
    whoShort: "Redemption es un sitio web cristiano, gratis y privado, que ayuda a personas en Texas a encontrar comida, una cama, duchas, una identificación, un teléfono y más. La ayuda es para todos.",
    howTitle: "Cómo usar Redemption gratis",
    step1: "Vaya a la biblioteca pública más cercana:",
    stepNoLibrary: "Pregunte a cualquier persona dónde está la biblioteca pública más cercana. O llame al 2-1-1.",
    from: (miles: string, dir: string, spot: string) => `A unas ${miles} al ${dir} de ${spot}`,
    here: "aquí",
    walk: (min: string) => `unos ${min} a pie`,
    farWalk: "muy lejos para caminar; pregunte por un autobús",
    hours: "Horario",
    step2: "Pida en el mostrador usar una computadora gratis. ¿No tiene tarjeta? Pida un pase de invitado.",
    step3: "Abra el internet y escriba:",
    step3b: "Luego toque lo que necesita.",
    scan: "O escanéelo con un teléfono",
    nearTitle: "Ayuda cerca de aquí",
    call211: "Llame al 2-1-1 a cualquier hora. Gratis, 24 horas, en cualquier idioma.",
    crisis: "¿En crisis? Llame o mande texto al 988.",
    emergency: "¿Emergencia? Llame al 9-1-1.",
    hopeTitle: "Una palabra de esperanza",
    prayer: "Una oración",
    footer: "Cada persona tiene valor. Cada persona puede ser redimida.",
    miles: (m: number) => (m < 0.1 ? "0.1 millas" : m < 10 ? `${m.toFixed(1)} millas` : `${Math.round(m)} millas`),
    dirs: ["norte", "noreste", "este", "sureste", "sur", "suroeste", "oeste", "noroeste"],
    cut: "cortar aquí",
  },
};
