// All words on the site, in English and Spanish.
// Keep sentences short and simple (about a 5th-grade reading level).
export const strings = {
  en: {
    siteName: "Redemption",
    tagline: "Free help in Texas",
    skip: "Skip to main content",
    nav: { home: "Find Help", map: "Map", id: "Get an ID", connected: "Phone & Internet", more: "More Help", handout: "Make Handouts", bible: "Free Bible" },
    langButton: "Español",
    langButtonLabel: "Cambiar a español",
    readAloud: "Read aloud",
    stopReading: "Stop reading",
    noSpeech: "Sorry, this computer cannot read aloud.",
    helperMode: "Helper mode",
    helperOn: "Helper mode is on",
    helperHint: "For volunteers and outreach workers helping someone.",

    heroTitle: "Every person has worth.",
    heroTitle2: "Every person can be redeemed.",
    heroText: "Find free food, a bed, a shower, an ID, and more in Texas. You are not alone.",
    heroCities: "Now in Austin, Houston, Dallas, San Antonio, Fort Worth, and El Paso.",
    heroNow: "Need help right now? Call 2-1-1. Free, 24 hours.",
    helpingSomeone: "Helping someone? Make handouts to pass out →",
    freeForAll: "All help is free and open to everyone. You do not have to believe anything to get help.",

    stepName: "What is your first name?",
    optional: "(you can skip this)",
    nameHelp: "We only use it to say hello on this screen. We never save it or send it anywhere.",
    namePlaceholder: "First name",
    hello: "Hello",
    helloWelcome: "You are welcome here.",

    stepWhere: "Where are you now?",
    whereHelp: "We use this only to find help close to you. It stays on this screen.",
    useLocation: "Use my location",
    finding: "Finding you…",
    locationDenied: "We could not get your location. Please type a ZIP code or pick a place below.",
    zipLabel: "Type a ZIP code",
    zipPlaceholder: "Example: 78701",
    zipShort: "ZIP code",
    or: "or",
    helperIntro: "For volunteers and outreach workers helping someone in person. Results show up as soon as you pick a place and a need.",
    helperName: "Their first name",
    helperNameHint: "Optional. Only printed on their Help Sheet.",
    helperWhere: "Where are you?",
    helperNeeds: "What do they need?",
    helperNeedPlace: "Pick where you are above to see help nearby.",
    helperPickOne: "Tap what they need to see places.",
    helperHandouts: "Make handouts",
    zipGo: "OK",
    zipUnknown: "That is not a Texas ZIP code we know. Please check it, or pick a place.",
    zipError: "We could not look up ZIP codes right now. Please pick a place from the list.",
    zipLooking: "Looking…",
    outsideTexas: "That location looks like it is outside Texas. Please type a ZIP code or pick a place.",
    locationTip: "On a library or shelter computer, a ZIP code or place works better than “Use my location.”",
    orPick: "Pick your city and a place near you",
    pickPlace: "Pick your city…",
    youAreNear: "Near",
    myLocation: "Your location",
    changePlace: "Change",
    needPlace: "First, tell us where you are in step 2. Then we can find help near you.",
    farAway: "We do not have places listed near you yet. Call 2-1-1 for free help close to you, any time.",

    stepNeed: "What do you need today?",
    needHelp: "Tap one or more.",
    showHelp: "Show me help",
    pickOne: "Tap at least one thing you need.",
    startOver: "Start over",
    clearInfo: "Clear my info",
    cleared: "Your info is cleared.",
    idleCleared: "For your privacy, we cleared your info because this screen was not used for a while.",

    needs: {
      food: "Food",
      shelter: "Shelter",
      showers: "Showers & Hygiene",
      id: "Get an ID",
      internet: "Internet & Phone",
      church: "Church",
      medical: "Medical Care",
      jobs: "Jobs",
      veterans: "Veterans",
      legal: "Legal Help",
    },
    categories: {
      library: "Library",
      shelter: "Shelter",
      "day-center": "Day center",
      food: "Food",
      church: "Church",
      clinic: "Clinic",
      hospital: "Hospital",
      "id-office": "ID office",
      jobs: "Jobs",
      veterans: "Veterans",
      legal: "Legal help",
    },

    resultsTitle: "Help near you",
    resultsFor: "Places for",
    closestFirst: "Closest places are first.",
    noResults: "We did not find a place for this. Please call 2-1-1. They can help.",
    printSheet: "Print My Help Sheet",
    printHint: "Take this paper with you. It has addresses, hours, and a map.",
    back: "Back",
    hours: "Hours",
    services: "Church services",
    phone: "Phone",
    bring: "What to bring",
    website: "Website",
    call: "Call",
    directions: "Map",
    servesMeals: "Serves meals",
    lastChecked: "Last checked",
    approxMap: "Map pins are close, but not exact. Use the address.",
    hoursNote: "Hours can change on holidays. Call to confirm.",
    showMore: "Show more places",
    walkNote: "Walking times are estimates.",

    filters: "Quick filters",
    within: "Distance",
    any: "Any",
    mealsOnly: "Serves meals",
    openOnly: "Open now",

    sheetTitle: "My Help Sheet",
    sheetFor: "For",
    sheetMade: "Made on",
    sheetStart: "Starting place",
    sheet211: "Need more help? Call 2-1-1 (free, 24 hours). Or call 877-541-7905.",
    sheetCrisis: "In crisis? Call or text 988, any time.",
    sheetVisit: "Find more help at",
    mapNorth: "N",
    mapYou: "You",

    footerVerse: "Verse of the day",
    footer211: "Need help now? Call 2-1-1",
    footer211b: "Free. Open 24 hours. Any language.",
    footerEmergency: "Emergency? Call 9-1-1.",
    footerPrivacy: "Private: no accounts, no tracking. Nothing you type is saved.",
    footerLinks: { privacy: "Privacy", flyer: "Make handouts" },
    footerMade: "Made with love for our neighbors across Texas.",
    verseNotice: "Scripture: World English Bible and King James Version (public domain). Spanish: Reina-Valera 1960 © Sociedades Bíblicas en América Latina, 1960; renewed © Sociedades Bíblicas Unidas, 1988. Used by permission.",

    allCategories: "All",
    mapTitle: "Map of free help in Texas",
    allCities: "All cities",
    cityLabel: "City",
    mapIntro: "Every place on this site. Pick a type to see just those places.",
    directoryTitle: "Full list",
  },
  es: {
    siteName: "Redemption",
    tagline: "Ayuda gratis en Texas",
    skip: "Ir al contenido principal",
    nav: { home: "Buscar Ayuda", map: "Mapa", id: "Sacar una ID", connected: "Teléfono e Internet", more: "Más Ayuda", handout: "Hacer Volantes", bible: "Biblia Gratis" },
    langButton: "English",
    langButtonLabel: "Switch to English",
    readAloud: "Leer en voz alta",
    stopReading: "Parar lectura",
    noSpeech: "Lo sentimos, esta computadora no puede leer en voz alta.",
    helperMode: "Modo ayudante",
    helperOn: "Modo ayudante encendido",
    helperHint: "Para voluntarios y trabajadores de alcance que ayudan a alguien.",

    heroTitle: "Cada persona tiene valor.",
    heroTitle2: "Cada persona puede ser redimida.",
    heroText: "Encuentre comida, una cama, una ducha, una identificación y más, gratis en Texas. No está solo.",
    heroCities: "Ahora en Austin, Houston, Dallas, San Antonio, Fort Worth y El Paso.",
    heroNow: "¿Necesita ayuda ahora? Llame al 2-1-1. Gratis, 24 horas.",
    helpingSomeone: "¿Ayuda a alguien? Haga volantes para repartir →",
    freeForAll: "Toda la ayuda es gratis y abierta para todos. No tiene que creer en nada para recibir ayuda.",

    stepName: "¿Cuál es su primer nombre?",
    optional: "(puede saltar esto)",
    nameHelp: "Solo lo usamos para saludarle en esta pantalla. Nunca lo guardamos ni lo enviamos.",
    namePlaceholder: "Primer nombre",
    hello: "Hola",
    helloWelcome: "Aquí es bienvenido.",

    stepWhere: "¿Dónde está ahora?",
    whereHelp: "Solo lo usamos para buscar ayuda cerca de usted. Se queda en esta pantalla.",
    useLocation: "Usar mi ubicación",
    finding: "Buscando…",
    locationDenied: "No pudimos obtener su ubicación. Escriba un código postal o elija un lugar abajo.",
    zipLabel: "Escriba un código postal",
    zipPlaceholder: "Ejemplo: 78701",
    zipShort: "Código postal",
    or: "o",
    helperIntro: "Para voluntarios y trabajadores de alcance que ayudan a alguien en persona. Los resultados aparecen en cuanto elija un lugar y una necesidad.",
    helperName: "Su primer nombre",
    helperNameHint: "Opcional. Solo se imprime en su Hoja de Ayuda.",
    helperWhere: "¿Dónde están?",
    helperNeeds: "¿Qué necesita?",
    helperNeedPlace: "Elija arriba dónde están para ver ayuda cerca.",
    helperPickOne: "Toque lo que necesita para ver lugares.",
    helperHandouts: "Hacer volantes",
    zipGo: "OK",
    zipUnknown: "No conocemos ese código postal de Texas. Revíselo o elija un lugar.",
    zipError: "No pudimos buscar códigos postales ahora. Elija un lugar de la lista.",
    zipLooking: "Buscando…",
    outsideTexas: "Esa ubicación parece estar fuera de Texas. Escriba un código postal o elija un lugar.",
    locationTip: "En una computadora de biblioteca o refugio, un código postal o un lugar funciona mejor que “Usar mi ubicación”.",
    orPick: "Elija su ciudad y un lugar cerca de usted",
    pickPlace: "Elija su ciudad…",
    youAreNear: "Cerca de",
    myLocation: "Su ubicación",
    changePlace: "Cambiar",
    needPlace: "Primero, díganos dónde está en el paso 2. Así podemos buscar ayuda cerca de usted.",
    farAway: "Todavía no tenemos lugares cerca de usted. Llame al 2-1-1 para recibir ayuda gratis cerca, a cualquier hora.",

    stepNeed: "¿Qué necesita hoy?",
    needHelp: "Toque una o más.",
    showHelp: "Muéstreme ayuda",
    pickOne: "Toque por lo menos una cosa que necesita.",
    startOver: "Empezar de nuevo",
    clearInfo: "Borrar mis datos",
    cleared: "Sus datos se borraron.",
    idleCleared: "Por su privacidad, borramos sus datos porque esta pantalla no se usó por un rato.",

    needs: {
      food: "Comida",
      shelter: "Refugio",
      showers: "Duchas e Higiene",
      id: "Identificación",
      internet: "Internet y Teléfono",
      church: "Iglesia",
      medical: "Atención Médica",
      jobs: "Trabajo",
      veterans: "Veteranos",
      legal: "Ayuda Legal",
    },
    categories: {
      library: "Biblioteca",
      shelter: "Refugio",
      "day-center": "Centro de día",
      food: "Comida",
      church: "Iglesia",
      clinic: "Clínica",
      hospital: "Hospital",
      "id-office": "Oficina de ID",
      jobs: "Trabajo",
      veterans: "Veteranos",
      legal: "Ayuda legal",
    },

    resultsTitle: "Ayuda cerca de usted",
    resultsFor: "Lugares para",
    closestFirst: "Los lugares más cercanos están primero.",
    noResults: "No encontramos un lugar para esto. Por favor llame al 2-1-1. Ellos pueden ayudar.",
    printSheet: "Imprimir Mi Hoja de Ayuda",
    printHint: "Lleve este papel con usted. Tiene direcciones, horarios y un mapa.",
    back: "Atrás",
    hours: "Horario",
    services: "Servicios de iglesia",
    phone: "Teléfono",
    bring: "Qué traer",
    website: "Sitio web",
    call: "Llamar",
    directions: "Mapa",
    servesMeals: "Sirve comidas",
    lastChecked: "Revisado",
    approxMap: "Los puntos del mapa son cercanos, no exactos. Use la dirección.",
    hoursNote: "Los horarios pueden cambiar en días festivos. Llame para confirmar.",
    showMore: "Ver más lugares",
    walkNote: "Los tiempos a pie son aproximados.",

    filters: "Filtros rápidos",
    within: "Distancia",
    any: "Todas",
    mealsOnly: "Sirve comidas",
    openOnly: "Abierto ahora",

    sheetTitle: "Mi Hoja de Ayuda",
    sheetFor: "Para",
    sheetMade: "Hecha el",
    sheetStart: "Punto de partida",
    sheet211: "¿Necesita más ayuda? Llame al 2-1-1 (gratis, 24 horas). O llame al 877-541-7905.",
    sheetCrisis: "¿En crisis? Llame o mande texto al 988, a cualquier hora.",
    sheetVisit: "Encuentre más ayuda en",
    mapNorth: "N",
    mapYou: "Usted",

    footerVerse: "Versículo del día",
    footer211: "¿Necesita ayuda ahora? Llame al 2-1-1",
    footer211b: "Gratis. Abierto 24 horas. En cualquier idioma.",
    footerEmergency: "¿Emergencia? Llame al 9-1-1.",
    footerPrivacy: "Privado: sin cuentas, sin rastreo. Nada de lo que escribe se guarda.",
    footerLinks: { privacy: "Privacidad", flyer: "Hacer volantes" },
    footerMade: "Hecho con amor para nuestros vecinos en todo Texas.",
    verseNotice: "Escrituras: Reina-Valera 1960 © Sociedades Bíblicas en América Latina, 1960; renovado © Sociedades Bíblicas Unidas, 1988. Usado con permiso. Inglés: World English Bible y King James Version (dominio público).",

    allCategories: "Todos",
    mapTitle: "Mapa de ayuda gratis en Texas",
    allCities: "Todas las ciudades",
    cityLabel: "Ciudad",
    mapIntro: "Todos los lugares de este sitio. Elija un tipo para ver solo esos lugares.",
    directoryTitle: "Lista completa",
  },
};

export type Lang = keyof typeof strings;
export type Strings = (typeof strings)["en"];
